CREATE DATABASE LOPO
GO
USE LOPO
GO
CREATE TABLE USUARIOS
(
	ID_USUARIOS INT IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	MAIL VARCHAR(100) NOT NULL,
	CONTRASENIA VARCHAR(100) NOT NULL
)
GO
CREATE PROCEDURE OBTENER_USUARIOS
	AS
	BEGIN
	SELECT * FROM USUARIOS
	END
GO
CREATE PROCEDURE ALTA_USUARIOS
	@NOMBRE VARCHAR(100),
	@MAIL VARCHAR(100),
	@CONTRASENIA VARCHAR(100)
	AS
	BEGIN
		INSERT INTO USUARIOS ( NOMBRE, MAIL, CONTRASENIA) VALUES ( @NOMBRE, @MAIL, @CONTRASENIA)
	END
GO
CREATE TABLE LIBROS
(
	AUTOR VARCHAR(100) NOT NULL ,
	TITULO VARCHAR(100) NOT NULL PRIMARY KEY,
	EJEMPLAR INT NOT NULL
)
GO
CREATE PROCEDURE OBTENER_LIBROS
AS
BEGIN
	SELECT * FROM LIBROS
END
GO
CREATE PROCEDURE ALTA_LIBROS
	@AUTOR VARCHAR(100),
	@TITULO VARCHAR(100),
	@EJEMPLAR INT 
	AS
	SET NOCOUNT ON
	BEGIN
		INSERT INTO LIBROS (AUTOR,TITULO,EJEMPLAR) VALUES (@AUTOR,@TITULO,@EJEMPLAR)
END
GO
CREATE PROCEDURE BAJA_LIBRO
	@TITULO VARCHAR(100)
AS
SET NOCOUNT ON
BEGIN
	IF NOT EXISTS( SELECT 1 FROM LIBROS WHERE TITULO = @TITULO )
	BEGIN 
		THROW 50001, 'ERROR, no HAY LIBROS con este titulo',1
	END


		DELETE FROM LIBROS WHERE TITULO = @TITULO
END
GO
CREATE PROCEDURE MODIFICAR_LIBRO
	@BORRAR VARCHAR(100),
	@AUTOR VARCHAR(100),
	@TITULO VARCHAR(100),
	@EJEMPLAR INT
	AS
	SET NOCOUNT ON
	BEGIN
		IF NOT EXISTS( SELECT 1 FROM LIBROS WHERE TITULO = @BORRAR)
			BEGIN
				THROW 50001, ' ERROR, No hay libros con este titulo',1;
			END
		BEGIN
			UPDATE LIBROS 
			SET
				AUTOR = @AUTOR,
				TITULO = @TITULO,
				EJEMPLAR = @EJEMPLAR
			WHERE TITULO = @BORRAR;
		END
	END
GO
